spring:
  # 配置默认数据源-HikariDataSource
  datasource:
    url: jdbc:mysql://localhost:3306/idc?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLocalSessionState=true&serverTimezone=UTC
    username: root
    password: tiger
    driverClassName: com.mysql.cj.jdbc.Driver
dubbo:
  application:
    name: apiGateway
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
logging:
  level:
    root: info
    com.liuapi.identity: debug
