spring:
  # 配置默认数据源-HikariDataSource
  datasource:
    url: jdbc:mysql://192.168.110.12:3306/idc?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLocalSessionState=true&serverTimezone=UTC
    username: root
    password: pubtrans
    driverClassName: com.mysql.cj.jdbc.Driver
dubbo:
  application:
    name: apiGateway
  registry:
    address: zookeeper://192.168.110.12:2181
  protocol:
    name: dubbo
    port: 29999
logging:
  level:
    root: info
    com.liuapi.identity: info
